load('shuzix0.mat') 
load('shuzix1.mat') 
load('shuzix2.mat') 
load('shuzix3.mat') 
load('shuzix4.mat') 
load('shuzix5.mat') 
load('shuzix6.mat') 
load('shuzix7.mat') 
load('shuzix8.mat') 
load('shuzix9.mat') 
load('shuzix10.mat') 
load('shuzix11.mat') 
load('shuzix12.mat') 
load('shuzix13.mat') 
load('shuzix14.mat') 
load('shuzix15.mat') 
load('shuzix16.mat') 

save shuzi.mat